export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Profile } from './Profile'
export { default as Register } from './Register'
export { default as Search } from './Search'
export { default as Video } from './Video'
export { default as VideoRequest } from './VideoRequest'