const videoActions = {
    SET_VIDEOS: 'SET_VIDEOS',
    SET_SEARCH_VIDEOS: 'SET_SEARCH_VIDEOS',
    REMOVE_SEARCH_VIDEOS: 'REMOVE_SEARCH_VIDEOS',
    SORT_LIKES: 'SORT_LIKES',
    SORT_DISLIKES: 'SORT_DISLIKES',
    SORT_OVERALL: 'SORT_OVERALL',
    SORT_HUMOR: 'SORT_HUMOR',
    SORT_INFORMATIVE: 'SORT_INFORMATIVE',
    SORT_PRODUCTION: 'SORT_PRODUCTION',
    SORT_CUTENESS: 'SORT_CUTENESs',
    SORT_SADNESS: 'SORT_SADNESS'
}

export default videoActions